### ISSUE TITLE
Incorrect new lines encoding in bitcoin signed messages

### ISSUE THREAD

**Issue by antonio-fr** [opendime/opendime#11]
Using various signatures verification tools, including the official Qt client, and I can't verify the provided example in https://github.com/opendime/opendime/blob/master/v2.4/sealed/advanced/verify.txt
This repository tells "these files were copied from a sample unit running version 2.4.0 of the firmware"
What's the reason of the invalid signature ? Are they faked data ? Is this using non-standard message signing ? bug in firmware?

**Comment by doc-hex** [comment]
Newlines are often a problem. Try to verify <https://github.com/opendime/opendime/blob/master/v2.4/sealed/advanced/verify2.txt> instead. It's just one line (nonce:...)

**Comment by antonio-fr** [comment]
Thanks. I investigated this issue. The message you provide is signed with CRLF line ending. But the "BITCOIN SIGNED MESSAGE" signed message standard impose to use only LF Linux/C++ line endings. That's because the most used Bitcoin wallets (bitcoin Qt and Electrum) are all using the [_toPlainText_ method on the Qt text document](https://doc.qt.io/qt-5.12/qtextdocument.html#toPlainText) object, and [that changes](https://forum.qt.io/topic/42464/qplaintextedit-eats-line-endings) the CRLF into LF. And according to this defacto standard, many verification (and signing) softwares are removing the CR character in the text verified. See [here for a BrainWallet derivative](https://github.com/weex/bitcoin-signature-tool/blob/master/js/brainwallet.js#L1435) (available online [here](https://reinproject.org/bitcoin-signature-tool/#verify)), and [FSV there](https://github.com/antonio-fr/Fast_Sign_Verify/blob/master/ECDSA_BTC.py#L215).

So there's an issue in the way the signature texts are generated by opendime. The firmware should convert the new lines into LF before adding header and signing. Or similarly, build the message directly with new lines as LF. The main benefit would be to allow the users to easily verify the provided message, using standard tools, using copy-paste. Else barely anyone can check the signature provided, and that ruins the "BITCOIN SIGNED MESSAGE" message format benefit.

**Comment by doc-hex** [comment]
Yes, that's the challenge for sure. Further points:
- there is no BIP which covers the ASCII armour or fine points such as newline treatment (AFAIK)
- IMHO, the original Core implementation was emulating RFC2550 <https://www.ietf.org/rfc/rfc2440.txt> which requires CR+LF
- you may want to consider the code in pycoin <https://github.com/richardkiss/pycoin/blob/master/pycoin/contrib/msg_signing.py> which converts/replaces newlines
- a first-class signature verifier would try the 'other' newline styles when hashing, since trying both does not impact security and accommodates newline changes that may have happened against the will of the user, such as during cut-n-paste operations.
- Opendime is emulating a DOS filesystem, so all text files have CR+LF just like DOS would do. 

We really need a BIP or two on this subject. Great chance to contribute!
