### ISSUE TITLE
Unable to verify serial for ATECC508A

### ISSUE THREAD

**Issue by duncancmt** [opendime/opendime#15]
The [trust features page](https://github.com/opendime/opendime/blob/master/whitepapers/opendime-trust-features.md?plain=1#L156-L158) remarks that the serial for the ATECC508A is laser etched and visible. Not only is this not visible (I used a jeweler's loupe), this appears to contradict [the part documentation](https://ww1.microchip.com/downloads/en/DeviceDoc/20005928A.pdf) (section 4). Is there another way to verify the serial number baked into the device certificate?

**Comment by doc-hex** [comment]
That document means the serial number is laser-etched onto individual dies (the chip itself, not the outside plastic). Those changes made by the laser set some ones and zeros so that the 508 knows its own serial number, and all messages that it signs with its private key include the serial number as a component. Therefore, the best/only way to verify the serial number is to check the signature it makes. That's exactly what "trustme.py" does. It picks a nonce (random number), and gets the 508 to sign it. That fresh signature is checked against the pubkey included in the x.509 certificate signed by the Opendime factory.

**Comment by duncancmt** [comment]
Ahh, now I understand. I apologize for my confusion and thank you very much for the clear explanation.
