### ISSUE TITLE
macOS : unable to verify screenshot dragged onto device

### ISSUE THREAD

**Issue by Sjors** [opendime/opendime#8]
I created a screenshot, shrunk it a bit so it fits on a fresh (v4) device, and dragged the PNG over. The device rebooted and macOS threw a tantrum about unsafe ejection as expected.

But when I run `python rngverify.py ~/the_screenshot.png` it fails with: `FAILED: You probably didn't record exactly the bytes written to this drive.` 

The two lines that are different between my device and `v2.4/sealed/advanced/rngverify.py` are `ADDRESS` and `CHIP_SERIAL`.

**Comment by doc-hex** [comment]
To achieve the byte-for-byte precision required for verification, you need to use `dd` to put the bytes onto the drive. Using drag-n-drop or `cp` isn't ideal because there are arbitrary writes to the metadata (FATFS) to support updating the file's directory listing and so on.

[See line 23 of rngverify.py for example](https://github.com/opendime/opendime/blob/a8567583293c1c6bd483597467430f617ece15ae/v2.4/unsealed/advanced/rngverify.py#L23)

**Comment by Sjors** [comment]
I see. I'll try that again some other time then.
